

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Demo.Core.EntityModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class OnBoadTaskEntities : DbContext
{
    public OnBoadTaskEntities()
        : base("name=OnBoadTaskEntities")
    {

        this.Configuration.LazyLoadingEnabled = false;

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }

    public virtual DbSet<tbl_Product> tbl_Product { get; set; }

    public virtual DbSet<tbl_ProductSold> tbl_ProductSold { get; set; }

    public virtual DbSet<tbl_Store> tbl_Store { get; set; }


    public virtual ObjectResult<GetSalesDetail_Result> GetSalesDetail(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalesDetail_Result>("GetSalesDetail", idParameter);
    }

}

}

